export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const SHOW_MESSAGE = "SHOW_MESSAGE";
export const SHOW_SIGNUP_MESSAGE = "SHOW_SIGNUP_MESSAGE";
export const SHOW_LOADING_INDICATOR = "SHOW_LOADING_INDICATOR";
